<?php


function myroute_breadcrumb_preprocess_breadcrumb(&$variables) {
  $_route_object = \Symfony\Cmf\Component\Routing\RouteObjectInterface::ROUTE_OBJECT;
  if (!empty($variables['breadcrumb'])) {


    $request = \Drupal::request();

    // Крошка на главную страницу
    $config = \Drupal::config('myroute_breadcrumb.settings');
    $breadcrumb_front_name = $config->get('breadcrumb_front_name');
    if (empty($breadcrumb_front_name)) {
      $breadcrumb_front_name = t('Home');
    }
    if ($variables['breadcrumb'][0]['url'] != '/') {
      $variables['breadcrumb'][-1] = [
        'text' => $breadcrumb_front_name,
        'url' => '/'
      ];
      ksort($variables['breadcrumb']);
    }
    else {
      $variables['breadcrumb'][0] = ['text' => $breadcrumb_front_name, 'url' => '/'];
    }




    // Удаляем ссылку если это сылка на текущую страницу
    if ($request->attributes->has($_route_object) && $route = $request->attributes->get($_route_object)) {
      // $curent_url = Url::createFromRequest($request)->toString();
      $curent_url = $_SERVER['REQUEST_URI'];
      foreach ($variables['breadcrumb'] as &$breadcrumb) {
        if ($breadcrumb['url'] == $curent_url) {
          unset($breadcrumb['url']);
        }
      }
    }


    // Если кол-во ссылок = 1, только на главную, то добавляем на текущую страницу
    if (count($variables['breadcrumb']) == 1) {
      /* @var $route \Symfony\Component\Routing\Route */
      if ($request->attributes->has($_route_object)) {
        if ($route = $request->attributes->get($_route_object)) {
          $title = \Drupal::service('title_resolver')
            ->getTitle($request, $route);
          $variables['breadcrumb'][] = ['text' => $title];
          $variables['#cache']['contexts'][0] = 'route';
        }
      }
    }

  }
}


